spring.application.name=gezecek

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.session.store-type=redis
spring.session.timeout=30m

# Flight API Configuration get from .env
flight.api.base-url=https://kiwi-com-cheap-flights.p.rapidapi.com
flight.api.key=${FLIGHT_API_KEY}
flight.api.host=${FLIGHT_API_HOST}
flight.api.timeout=30